[package]
name = "Project"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
aes-gcm = "0.10.3" 
permutation_iterator = "0.1.2"
serde = { version = "1.0", features = ["derive"]}
csv = "1.3.1"